name: remote ssh command
on:
  create
jobs:
  name: Build
  runs-on: ubuntu-latest
  steps:
  - name: executing remote ssh commands
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    port: 22
    script: |
      cd /var/www/
      git clone git@github.com:PupilPay/Portal.git ${ GITHUB_REF##*/ }
      cd ${ GITHUB_REF##*/ }
      git checkout -b ${ GITHUB_REF##*/ }
      composer install --no-interaction
      npm install
      cp .env.example .env
      sed -i 's/branchname/${ GITHUB_REF##*/ }/g' .env
      sed -i 's/dbpass/${{ secrets.PASSWORD }}/g' .env
      sed -i 's/mailpass/${{ secrets.MAIL_PASS }}/g' .env
      mysql -u root -p${{ secrets.PASSWORD }} -e "CREATE DATABASE ${ GITHUB_REF##*/ };"
      php artisan migrate
      chmod -R 755 storage
      chown -R www-data:www-data storage
      php artisan key:generate
      sed -i 's/branchname/${ GITHUB_REF##*/ }/g' apache.conf
      cp apache.conf /etc/apache2/sites-enabled/${ GITHUB_REF##*/ }.conf
      service apache2 restart